### PR TITLE
Add build scripts & CI configuration

### PR DESCRIPTION
**Pull request by jatha**
This PR contains scripts that are able to build an archlinux-arm image with the tools in this repository installed. Moreover a CI config for gitlab ci is present, which builds an image for every commit and checks, wether the image boots in the xilinx-qemu. It should close https://lab.apertus.org/T697.

The pipeline for this PR can be found at https://gitlab.com/nein/beta-software/pipelines/13506162. 

However, some things in the build process are not finished or discussed or perfect:
* The github -> gitlab bridge scripts are somehow not working at the moment. I suspect that the http trigger at github is wrong configured. Someone with access to the github repo will need to fix this.
* U-Boot and the FPGA bitstream are currently dowloaded as static binary blobs and not build from source. This should definitly change in the future.
* The images are completely untested on real hardware at the moment. Could anyone try the generated image on a real microzed?
* The image structure has some differences, which are not discussed yet, to the axiom-beta images we currently have:
  * Only 2 partitions: one boot partition and one mixed OS/tools partition. I think this is handy during development and avoids a lot of fussing. But we have do discuss this
  * I introduced a tool called `axiom-update`, which does a system upgrade, pulls the latest souces from git, builds and installs them. I think this is handy during development.
  * The clone of this repo is located under `/opt/`. All the scripts and binary tools are linked to `/usr/local/bin/axiom-*`. This allows the user to list all of our tools by typing `axiom-<tab>`.
  * I introduced an `apertus` user (with password axiom) which is not root but has sudo-privileges. Moreover the login as root for ssh is now disabled.
  * The daemon is currently not installed.
  * The image is most likely very incomplete compared to the others.

However, I think we can merge the changes before all those issues are resolved and begin with a incomplete but working CI system, which would already be a step forwards :).

PS: Feel free to change anything, as most of the things are just based on assumptions and bad shell hacking ;)

### CODE REVIEW

**Comment by BAndiT1983** [comment]
Daemon is getting some new things at the moment, also an install script, which can be adjusted if required, as i don't know the details of the final image yet. It was made for easier testing while developing, for now.

**Comment by jatha** [comment]
yeah just feel free to add your stuff to the build-scripts. A good place to install the daemon would be the `build_tools/inner/install.sh`, which is run in a chroot of the beta.

**Comment by sp-apertus** [comment]
Great progress! Well done!

**Comment by sp-apertus** [comment]
Pushed a few cosmetically minor changes.

To have the naming of the project in a consistent way please write "AXIOM" (all caps) or if its in a path/Linux software name use all lowercase "axiom".

Same with "apertus°", all lower case and with degree symbol if possible.

**Pull request merged**
