### PR TITLE
Begin Restructuring

### PR DESCRIPTION
**Pull request by jatha**
The current structure and state of documentation is not really inviting to hack around and build the software. To improve this situation i merged the cleaner `fullstack` branch, updated all the stuff to the state of `master` and added a few own ideas. In many places i didnt knew what a specific directory was doing (eg.: whats the difference between `web/` and `axiom_beta_control_daemon/`?; whats does all the `cmv_*` tools do?). It would be great if anyone could write some documentation for this.

Anyway, this PR is not intendet to be merged. It should just show some issues and be a proposal to overcome this. Maybe someone with more in-depth knowledge of the code could adopt the ideas?

### CODE REVIEW

**Comment by sp-apertus** [comment]
Great jatha that you start this effort!

cmv_snap3 is the tool to capture still images: https://wiki.apertus.org/index.php/AXIOM_Beta/AXIOM_Beta_Software#Capture_an_image

cmv_hist3 outputs histogram real time data:
https://wiki.apertus.org/index.php/AXIOM_Beta/AXIOM_Beta_Software#Image_Histogram

cmv_perf3 output current acquisition and output FPS

cmv_train3 is executed when starting up the camera typically and initializes (trains) the communication with the image sensor. Its required to be done before acquiring the first image.

**Comment by jatha** [comment]
should we coppy the wiki to the corresponding directories in this repo?

maybe it would make sense to generate either the wiki form documentation in github? I would find it quite handy to have the code and the documentation in the same place/repo. (the [https://wiki.lineageos.org/contributing.html](linageos wiki) is a good example for doing this

**Comment by sp-apertus** [comment]
I would avoid manually copying/adding anything, it will mean a nightmare to maintain up to date once the wiki changes, etc.

We could add a Readme file inside each subfolder containing the links to the relevant wiki URLs maybe?

**Comment by jatha** [comment]
adding a Readme with a Url to each subfolder would be a big step forward :) I would prefer to have the documentation sitting next to the code but this is not important for me. Are you going to add them to this PR or to the master?

**Comment by BAndiT1983** [comment]
What does this sentence mean: "whats the difference between web/ and axiom_beta_control_daemon/"?

**Comment by sp-apertus** [comment]
Jatha, can you please create a new PR that does not include the changes in the fullstack branch?
We cannot merge this as-is.

**Comment by sp-apertus** [comment]
I added one readme as template here: https://github.com/apertus-open-source-cinema/beta-software/tree/master/cmv_snap3

Feel free to add additional ones in new PRs

**Comment by jatha** [comment]
@BAndiT1983 doesnt both of the directories try to implement somekind of web control/rest api?

@sp-apertus what kind of changes from the fullstack branch? I tried to take all the code from the master and only additions like script and submodules from fullstack.

**Comment by BAndiT1983** [comment]
Daemon tries to implement a central place to manage settings and similar stuff on camera. Didn't know about the other web GUI project files, will consider to merge them, if they still fit, when daemon matured a bit more.

**Comment by sp-apertus** [comment]
The stuff in /http is a collection of webGUIs ported from the AXIOM Alpha. These set camera parameters running commandline bash scripts through PHP, eventually they should be adapted to use the daemon.
They have not been tested much with the beta yet so its possible they are partly in none working state currently.

**Comment by sp-apertus** [comment]
The fullstack branch is for a modified beta hardware stack by Mavrx, see https://wiki.apertus.org/index.php/Case_Studies/AXIOM_Beta - no merging recommended

**Pull request closed without merging**
